'''Modifiable parameters of the project'''

# The Slack app token - can be generated by Slack API 
OAUTH_TOKEN = 'xoxb-1591136001063-1591149264087-GpKJA7IfXsQrlcRIhJtPT7Dx' 

# The Slack channel name
SLACK_CHANNEL = '#restaurante'

# The employees can only request their menu until 11 AM
HOUR = 18 # AM CLT

